version: '3.7'

services:
  web:
    build: .
    command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=ocg6!vh^m8n6zg!f59s^m)%=myucqv9i8zj*4glc!3*s2^7_rv
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51HMsoHLDHddFvdLfK79jmn10bUE1A389hazNLBeMo0jyDCSXkK0ZV1xBgbDrzKToZ6qbOUMxREm1jKioDl0gFNh600CgAxb64l
      - STRIPE_TEST_SECRET_KEY=sk_test_51HMsoHLDHddFvdLf7oBzr3kxx5nHUQfSMq2h8zmHUWOlwMV3VrK9dDzGKAwgB0YW5EUFdammQGBreexrzVi24kIN00cDp6zBLT
    volumes:
      - .:/code
    ports:
       - 8000:8000
    depends_on:
        - db
  db: 
    image: postgres:11
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
     - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes: 
  postgres_data: