# Generated by Django 2.2.7 on 2020-09-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_review_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='buy',
        ),
        migrations.RemoveField(
            model_name='review',
            name='cover',
        ),
    ]
