# Generated by Django 2.2.7 on 2020-09-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=50, max_digits=6),
            preserve_default=False,
        ),
    ]
