# Generated by Django 2.2.7 on 2020-09-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='buy',
        ),
    ]
